services:

  phpapache:
    build: ./app
    ports:
      - "8080:80"
    volumes:
      # on met la config apache dans le container au bon endroit apache sous le nom 000-default.conf
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      # on transmet les infos de config locales dans le conteneur (ex: ajouter des images)
      - ./app:/var/www
      
    networks:
      - techtrendznet
    depends_on:
      - db   

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    networks:
      - techtrendznet

  phpmyadmincinescore: 
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: $PMA_ARBITRARY
            PMA_HOST: $PMA_HOST
            PMA_USER: $PMA_USER
            PMA_PASSWORD: $PMA_PASSWORD
            UPLOAD_LIMIT: $UPLOAD_LIMIT
        ports:
          - "8899:80"
        depends_on:
          - db
        networks:
         - techtrendznet
        
networks:
  techtrendznet:
    driver: bridge


  